BackEnd/src/app.js
BackEnd/src/db/models/game-models.js
BackEnd/src/db/models/score-models.js
BackEnd/src/db/schemas/game-schema.js
BackEnd/src/routers/game-routers.js
BackEnd/src/routers/score-routers.js
BackEnd/src/services/game-service.js
BackEnd/src/services/index.js
BackEnd/src/services/score-service.js

백엔드 CRUD 기본 기능 완성

---

FrontEnd/package-lock.json
FrontEnd/package.json
FrontEnd/src/App.tsx
FrontEnd/src/pages/communityPage/community.tsx

main branch 버전 관리를 위해 한번 병합작업 진행함

Feature yj => feature PR

---

FrontEnd/src/pages/userPages/changePassword.tsx
FrontEnd/src/pages/userPages/login.tsx
FrontEnd/src/pages/userPages/register.tsx
package-lock.json

feature_mw 생성 및 user 관련 페이지 생성

---

BackEnd/src/db/schemas/comment-schema.js
BackEnd/src/db/schemas/post-schema.js

Post schema 생성
Comment Schema 수정
Community Page 생성

[add] post, comment schema 생성, Community Page 생성

---

BackEnd/src/db/models/user-models.js
BackEnd/src/routers/user-routers.js
BackEnd/src/services/user-service.js

유저 관련 models, router, service 세부 내용 수정

feature_mw to feature

---

FrontEnd/src/pages/gamePages/gameLayout.tsx

[add] 게임실행 페이지에 main-body/footer 컴포넌트 적용

[main] 메인페이지 컴포넌트 게임페이지에 적용함

---

FrontEnd/src/pages/userPages/login.tsx
FrontEnd/src/pages/userPages/signup.tsx

[add] 회원가입 페이지에 mainbody/footer 추가

[merge/main] 회원가입 페이지 하단 바 추가

---

FrontEnd/src/App.tsx
FrontEnd/src/pages/mainPage/main-body.tsx
FrontEnd/src/pages/mainPage/main-footer.tsx
FrontEnd/src/pages/mainPage/main.tsx
FrontEnd/src/pages/myPage/mypage.tsx

추후 통일 필요하다면 추가로 수정해야함.
일단은 소문자로 통일하는 것으로 하였음.

[merge] 파일명(소문자로 시작)에 맞게 import 경로 수정

---

BackEnd/src/app.js
BackEnd/src/db/index.js
BackEnd/src/db/models/comment-models.js
BackEnd/src/routers/comment-routers.js
BackEnd/src/routers/index.js
BackEnd/src/services/comment-service.js
BackEnd/src/services/index.js

[add] Comment API 구현

---

FrontEnd/src/App.tsx
FrontEnd/src/pages/userPages/signup.tsx

회원가입 페이지 CSS 추가

---

FrontEnd/.prettierrc
FrontEnd/src/pages/mainPage/main-body.tsx
FrontEnd/src/pages/mainPage/main-footer.tsx

prettierrc 파일 추가, 메인페이지 footer 레이아웃 변경

---

FrontEnd/src/App.tsx

App.tsx 경로 순서 수정

---

BackEnd/src/app.js
BackEnd/src/db/index.js
BackEnd/src/db/models/category-models.js
BackEnd/src/db/models/game-models.js
BackEnd/src/db/schemas/category-schema.js
BackEnd/src/db/schemas/game-schema.js
BackEnd/src/routers/category-routers.js
BackEnd/src/routers/game-routers.js
BackEnd/src/services/category-service.js
BackEnd/src/services/game-service.js
BackEnd/src/services/index.js
FrontEnd/src/pages/mainPage/main-body.tsx

1. [backend] category 관련 기능 추가, category로 game목록 검색하는 기능 추가
2. [frontend] Axios 요청으로 백엔드에서 카테고리목록, 게임목록을 불러와서 렌더링하도록 수정

merge [feature_dw] to [feature] 변경점 다수

---

FrontEnd/.gitignore
FrontEnd/package-lock.json
FrontEnd/src/index.tsx
FrontEnd/src/pages/mainPage/main-body.tsx

이후 서버에서 이미지 불러올 것을 대비하여 process.env 형태로 변경하였음.

메인페이지 주소들을 환경변수로 변경함

---

BackEnd/README.md
BackEnd/src/db/models/user-models.js
BackEnd/src/routers/user-routers.js
BackEnd/src/services/user-service.js
FrontEnd/src/App.tsx
FrontEnd/src/pages/myPage/avartar-change.tsx
FrontEnd/src/pages/myPage/components/profile.tsx
FrontEnd/src/pages/myPage/nickname-change.tsx
FrontEnd/src/pages/myPage/password-change.tsx
FrontEnd/src/pages/myPage/postWithComment.tsx
FrontEnd/src/pages/userPages/login.tsx
FrontEnd/src/pages/userPages/signup.tsx
FrontEnd/src/pages/userPages/users.tsx

유저 api 수정 및 유저 검색 기능 추가

---

BackEnd/src/db/schemas/score-schema.js
BackEnd/src/db/schemas/user-schema.js
FrontEnd/src/components/Games/StopWatch/controller/controller.tsx
FrontEnd/src/components/Games/StopWatch/recorder/recorder.tsx
FrontEnd/src/components/Games/StopWatch/timeStop.css
FrontEnd/src/components/Games/StopWatch/timeStop.tsx
FrontEnd/src/pages/mainPage/main-body.tsx
FrontEnd/src/pages/mainPage/main-footer.tsx
FrontEnd/src/pages/mainPage/main-header.tsx
FrontEnd/src/pages/mainPage/main.tsx

[add] gamemode 관리 state 추가
[modified] footer bar 카테고리버튼 사이즈수정
[modified] 모드변경버튼 css 수정
[add] 기록제출API (post) 작성
[add] 게임모드 변경기능(연습/도전) 추가
[modified] 링크 주소 일부 변경, 메인페이지 시작버튼 기능 일부 수정
[modified] score 스키마 수정(데이터 저장형식 변경)

[merge] feature_dw to feature 변경사항 다수

---

BackEnd/README.md

백엔드 README.md 파일 수정 (게임, 게임기록, 카테고리 API명세)

[merge] "feature dw" to "feature"

---

BackEnd/README.md
BackEnd/src/db/models/score-models.js
BackEnd/src/routers/category-routers.js
BackEnd/src/routers/score-routers.js
FrontEnd/src/components/Games/StopWatch/controller/controller.tsx
FrontEnd/src/components/Games/StopWatch/recorder/recorder.tsx
FrontEnd/src/pages/mainPage/main-body.tsx

[[modified] 카테고리 전체조회 API 콘솔 삭제(모든 페이지에서 계속 출력됨)]
[[modified] 10초게임 평균점수 출력방식 변경(gap => accuracy)]
[[modified] Score API명세 최신화]
[[modified] query parameter로 가져올 랭킹 갯수를 선택가능하도록 설정

10초게임 기록데이터 관련 일부 수정, score API관련 수정(상세내용 comment확인)

---

FrontEnd/src/components/Boards/PostPage.tsx

[add] 게시물 줄 변경 구현

---

BackEnd/src/db/models/comment-models.js
BackEnd/src/routers/comment-routers.js
FrontEnd/src/components/Boards/CreatePost.tsx
FrontEnd/src/components/Boards/DeletePostComponent.tsx
FrontEnd/src/components/Boards/PostPage.tsx
FrontEnd/src/components/Comments/CommentComponent.tsx
FrontEnd/src/components/Comments/CommentList.tsx
FrontEnd/src/components/Comments/CreateComment.tsx
FrontEnd/src/components/Comments/DeleteComment.tsx
FrontEnd/src/components/Comments/PatchComment.tsx
FrontEnd/src/pages/communityPage/patchPage.tsx

[add] 댓글 수정, 삭제 api 연결

---

BackEnd/src/routers/user-routers.js
FrontEnd/src/components/Users/LoginForm.tsx
FrontEnd/src/pages/userPages/login.tsx

로그인 폼 컴포넌트 분리 및 유저 정보 조회 API 경로 수정

로그인 폼 컴포넌트 분리 및 유저 정보 조회 API 경로 수정 

---

BackEnd/src/db/models/comment-models.js
BackEnd/src/db/models/post-models.js
FrontEnd/src/components/Boards/CreatePost.tsx
FrontEnd/src/components/Boards/NoticeComponent.tsx
FrontEnd/src/components/Boards/PostPage.tsx
FrontEnd/src/components/Comments/CommentComponent.tsx
FrontEnd/src/components/Comments/CreateComment.tsx
FrontEnd/src/components/Comments/PatchComment.tsx
FrontEnd/src/pages/communityPage/patchPage.tsx

[fix] post, comment 유저 API 연결

---

BackEnd/src/db/models/post-models.js
BackEnd/src/services/user-service.js
FrontEnd/src/components/Boards/CreatePost.tsx
FrontEnd/src/components/Boards/NoticeComponent.tsx

[fix] 게시판 오류 수정, css 수정

---

BackEnd/src/db/models/score-models.js
FrontEnd/src/pages/adminPage/info/gameAddOrEdit.tsx
FrontEnd/src/pages/adminPage/info/gameCategory.tsx
FrontEnd/src/pages/adminPage/info/gameInfoEdit.tsx
FrontEnd/src/pages/mainPage/main.tsx

명예의전당 검색 시 검색 기준 변경 gameId => gameUrl

Feature dw

---

BackEnd/src/db/models/post-models.js
BackEnd/src/routers/post-routers.js
BackEnd/src/services/post-service.js

[fix] 유저Post GET 라우터 수정

---

FrontEnd/src/pages/mainPage/main-footer.tsx

[Add] 로그아웃 기능 추가

---

FrontEnd/src/components/Games/StopWatch/recorder/recorder.tsx

modified]recorder scores post 요청 코드 수정

Feature sk

---

FrontEnd/src/components/Comments/CreateComment.tsx
FrontEnd/src/components/Comments/DeleteComment.tsx
FrontEnd/src/components/Comments/PatchComment.tsx

[fix] comment 작성, 수정, 삭제 시 자동으로 reload 되도록 구현

[fix] comment 작성, 수정, 삭제 시 자동으로 reload 되도록 구현

---

FrontEnd/src/components/CertBoards/CertDeleteComponent.tsx
FrontEnd/src/components/CertBoards/CertPostPage.tsx
FrontEnd/src/components/FreeBoards/DeletePostComponent.tsx
FrontEnd/src/components/FreeBoards/PostPage.tsx

[fix] 게시물의 길이에 따른 스크롤 구현

---

BackEnd/README.md
BackEnd/src/db/models/user-models.js
BackEnd/src/middlewares/login-required.js
BackEnd/src/routers/user-routers.js
BackEnd/src/services/user-service.js
FrontEnd/src/pages/myPage/components/profile.tsx
FrontEnd/src/pages/myPage/nickname-change.tsx
FrontEnd/src/pages/userPages/login.tsx

[add] 마이페이지 닉네임 변경 API 추가

---

BackEnd/src/db/models/user-models.js
BackEnd/src/routers/user-routers.js
BackEnd/src/services/user-service.js
FrontEnd/src/pages/myPage/nickname-change.tsx
FrontEnd/src/pages/myPage/password-change.tsx

[add] 마이페이지 비밀번호 변경 기능 추가

---

FrontEnd/src/pages/userPages/login.tsx
FrontEnd/src/pages/userPages/signup.tsx

[refactor] userPage 내 불필요한 console 삭제

[refactor] userPage 내 불필요한 console 삭제

---

FrontEnd/src/components/CertBoards/CertDeleteComponent.tsx
FrontEnd/src/components/CertBoards/CertPostPage.tsx
FrontEnd/src/components/CertBoards/CreateCertPost.tsx
FrontEnd/src/components/Comments/CommentComponent.tsx
FrontEnd/src/components/Comments/CommentList.tsx
FrontEnd/src/components/Comments/CreateComment.tsx
FrontEnd/src/components/Comments/DeleteComment.tsx
FrontEnd/src/components/Comments/PatchComment.tsx
FrontEnd/src/components/FreeBoards/CreateFreePost.tsx
FrontEnd/src/components/FreeBoards/DeletePostComponent.tsx
FrontEnd/src/components/FreeBoards/NoticeComponent.tsx
FrontEnd/src/components/FreeBoards/Pagination.tsx
FrontEnd/src/components/FreeBoards/PostPage.tsx

[refactor] any 타입을 정확한 타입으로 수정

[refactor] any 타입을 정확한 타입으로 수정

---

FrontEnd/src/pages/RankingPage/ranking.tsx
FrontEnd/src/pages/communityPage/Community.tsx
FrontEnd/src/pages/gamePages/gameLayout.tsx
FrontEnd/src/pages/gamePages/gameOver.tsx
FrontEnd/src/pages/mainPage/main.tsx
FrontEnd/src/pages/mainPage/mainBody.tsx
FrontEnd/src/pages/mainPage/mainFooter.tsx
FrontEnd/src/pages/mainPage/mainHeader.tsx
FrontEnd/src/pages/myPage/mypage.tsx
FrontEnd/src/pages/userPages/login.tsx
FrontEnd/src/pages/userPages/signup.tsx

1. [fix] 파일명 컨벤션에 맞게 변경, 모듈 호출경로 변경
2. 미사용 모듈 삭제

[Merge] feature_dw into Dev

---

FrontEnd/package-lock.json
FrontEnd/package.json
FrontEnd/src/components/Boards/DeletePostComponent.tsx
FrontEnd/src/components/Boards/NoticeComponent.tsx
FrontEnd/src/components/Boards/PostPage.tsx
FrontEnd/src/components/Comments/DeleteComment.tsx
FrontEnd/src/pages/communityPage/PatchPage.tsx

[Merge] dev merge

---

FrontEnd/src/pages/mainPage/mainBody.tsx
FrontEnd/src/pages/mainPage/mainFooter.tsx
FrontEnd/src/pages/mainPage/mainHeader.tsx
FrontEnd/src/pages/mainPage/mainStyle.ts

[Merge] Feature dw into Dev

---

FrontEnd/src/components/Boards/NoticeComponent.tsx
FrontEnd/src/components/Comments/CommentComponent.tsx
FrontEnd/src/utils/Pagination.tsx

[Fix] 페이지네이션 페이지 개수 5개씩 보이도록 구현
[Fix] 로그인 된 유저만 댓글 쓰기가 가능하도록 수정

[merge] dev merge 진행
